Removed shopping cart reference from header
mitodl/mitx-theme pull request #118
Opened 2020-11-09 09:37 UTC by asadiqbal08

#### What are the relevant tickets?
[issue#27](https://github.com/mitodl/mitxpro-theme/issues/27)

#### What's this PR do?
Shoppingcart has been almost deprecated for quite some time so it make sense to remove the shopping cart reference from this theme repo.

#### How should this be manually tested?
Installed the mitx-theme repo with edx-platform master and open any course.

2020-11-09 11:02 UTC, arslanashraf7 requested changes
I suppose we will need to remove cart-related changes from https://github.com/mitodl/mitx-theme/blob/asadiqbal08/remove-shopingcart-references/lms/templates/header/navbar-authenticated.html as well.

2020-11-09 12:04 UTC, asadiqbal08 commented
@arslanashraf7 can u point out what I missed over this PR and the file as you pointed above  ?

2020-11-10 12:49 UTC, HamzaIbnFarooq approved these changes
Kindly change the base branch to `koa`, otherwise looks good to me.

2020-11-12 11:04 UTC, arslanashraf7 approved these changes
Looks good 👍

2020-11-12 11:05 UTC, merged